LogIn= //span[contains(text(),'Login')]
UserName= //input[@type='text' and  @name='username']
Password= //input[@type='password' and  @name='password']
Menue= //span[@class="x-btn-icon-el x-btn-icon-el-aetextlink-small aegrid-menuhamburgerwhite "]
MenuSearch= //input[@role="textbox" and contains(@placeholder,'Search.')]
MyRequest= //div[contains(text(),'Access Request') or contains(text(),'My Request')]
PageTitle= Requests
Create= //span[@id='button-1084-btnInnerEl' and contains(text(),'Create')]
RequestSearch= //input[@placeholder='Search or Filter Request Type']
CardholderOnboardinhg= //h4[contains(text(),'Cardholder Onboarding with badge')]
FirstName= //input[@placeholder='Enter First Name' and @autocorrect='off']
LastName= //input[@placeholder='Enter Last Name' and @autocorrect='off']
WorkLocation= //label[contains(text(),'Select Work Location')]
SystemParameter= //span[@id='tab-2197-btnInnerEl' and contains(text(),'System Parameters')]
ProvisioningCheckBox = //input[@id='baseCheckBox-1826-inputEl']
LenelURLInput = //input[@id='baseText-1916-inputEl']