humana_master_internal:https://humana-master.internal.alertenterprisecloud.com/
humana_release_internal:https://humana-release.internal.alertenterprisecloud.com/
humana_dev:https://humana-dev.hsc.alertenterprisecloud.com
humana_uat:https://humana-uat.alerthsc.com